INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (1, 'Can add leito', 1, 'add_leito');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (2, 'Can change leito', 1, 'change_leito');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (3, 'Can delete leito', 1, 'delete_leito');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (4, 'Can view leito', 1, 'view_leito');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (5, 'Can add medico', 2, 'add_medico');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (6, 'Can change medico', 2, 'change_medico');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (7, 'Can delete medico', 2, 'delete_medico');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (8, 'Can view medico', 2, 'view_medico');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (9, 'Can add paciente', 3, 'add_paciente');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (10, 'Can change paciente', 3, 'change_paciente');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (11, 'Can delete paciente', 3, 'delete_paciente');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (12, 'Can view paciente', 3, 'view_paciente');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (13, 'Can add setor', 4, 'add_setor');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (14, 'Can change setor', 4, 'change_setor');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (15, 'Can delete setor', 4, 'delete_setor');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (16, 'Can view setor', 4, 'view_setor');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (17, 'Can add paciente_ leito', 5, 'add_paciente_leito');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (18, 'Can change paciente_ leito', 5, 'change_paciente_leito');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (19, 'Can delete paciente_ leito', 5, 'delete_paciente_leito');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (20, 'Can view paciente_ leito', 5, 'view_paciente_leito');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (21, 'Can add ocorrencia', 6, 'add_ocorrencia');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (22, 'Can change ocorrencia', 6, 'change_ocorrencia');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (23, 'Can delete ocorrencia', 6, 'delete_ocorrencia');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (24, 'Can view ocorrencia', 6, 'view_ocorrencia');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (25, 'Can add log entry', 7, 'add_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (26, 'Can change log entry', 7, 'change_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (27, 'Can delete log entry', 7, 'delete_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (28, 'Can view log entry', 7, 'view_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (29, 'Can add permission', 8, 'add_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (30, 'Can change permission', 8, 'change_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (31, 'Can delete permission', 8, 'delete_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (32, 'Can view permission', 8, 'view_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (33, 'Can add group', 9, 'add_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (34, 'Can change group', 9, 'change_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (35, 'Can delete group', 9, 'delete_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (36, 'Can view group', 9, 'view_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (37, 'Can add user', 10, 'add_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (38, 'Can change user', 10, 'change_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (39, 'Can delete user', 10, 'delete_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (40, 'Can view user', 10, 'view_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (41, 'Can add content type', 11, 'add_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (42, 'Can change content type', 11, 'change_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (43, 'Can delete content type', 11, 'delete_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (44, 'Can view content type', 11, 'view_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (45, 'Can add session', 12, 'add_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (46, 'Can change session', 12, 'change_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (47, 'Can delete session', 12, 'delete_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (48, 'Can view session', 12, 'view_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (49, 'Can add hospital', 13, 'add_hospital');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (50, 'Can change hospital', 13, 'change_hospital');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (51, 'Can delete hospital', 13, 'delete_hospital');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (52, 'Can view hospital', 13, 'view_hospital');