# Generated by Django 2.2.1 on 2019-05-23 22:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(default='A', max_length=2)),
                ('status', models.CharField(default='L', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(default='', max_length=6)),
                ('email', models.EmailField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=250)),
                ('ig', models.CharField(default='', max_length=10)),
                ('idade', models.CharField(default='', max_length=10)),
                ('peso_nasc', models.IntegerField(default=0)),
                ('peso_atual', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente_Leito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Leito')),
                ('pac', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Setor'),
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(default='', max_length=300)),
                ('dieta', models.CharField(default='', max_length=100)),
                ('acesso_venoso', models.CharField(default='Não', max_length=5)),
                ('antibiotico', models.CharField(default='Não', max_length=5)),
                ('medicamentos', models.TextField(default='', max_length=400)),
                ('ventilacao', models.CharField(default='Ar ambiente', max_length=100)),
                ('fototerapia', models.CharField(default='Não', max_length=5)),
                ('exames', models.TextField(default='', max_length=500)),
                ('conduta', models.TextField(default='', max_length=500)),
                ('data_add', models.DateTimeField(default=datetime.datetime(2019, 5, 23, 22, 35, 19, 895701, tzinfo=utc), editable=False)),
                ('data_modif', models.DateTimeField(default=datetime.datetime(2019, 5, 23, 22, 35, 19, 895747, tzinfo=utc))),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Medico')),
                ('pac', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Paciente')),
            ],
        ),
    ]
