# Generated by Django 3.1 on 2020-09-24 08:04

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=250)),
                ('sigla', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Leito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('situacao', models.CharField(default='A', max_length=2)),
                ('status', models.CharField(default='L', max_length=2)),
                ('hospital', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('crm', models.CharField(max_length=6)),
                ('hospital', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.hospital')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(default='', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=250)),
                ('ig', models.CharField(default='', max_length=10)),
                ('idade', models.CharField(default='', max_length=10)),
                ('peso_nasc', models.IntegerField(default=0)),
                ('peso_atual', models.IntegerField(default=0)),
                ('tcle', models.BooleanField(default=False)),
                ('status', models.CharField(default='', max_length=1)),
                ('data_add', models.DateTimeField(default=datetime.datetime(2020, 9, 24, 8, 4, 43, 525047, tzinfo=utc), editable=False)),
                ('data_modif', models.DateTimeField(default=datetime.datetime(2020, 9, 24, 8, 4, 43, 525111, tzinfo=utc))),
                ('leito', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.leito')),
                ('log_med', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.medico')),
                ('setor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(default='', max_length=300)),
                ('dieta', models.CharField(default='', max_length=100)),
                ('acesso_venoso', models.CharField(default='Não', max_length=40)),
                ('antibiotico', models.CharField(default='Não', max_length=100)),
                ('medicamentos', models.TextField(default='', max_length=400)),
                ('ventilacao', models.CharField(default='Ar ambiente', max_length=100)),
                ('fototerapia', models.CharField(default='Não', max_length=5)),
                ('exames', models.TextField(default='', max_length=500)),
                ('conduta', models.TextField(default='', max_length=500)),
                ('recomendacoes', models.TextField(default='', max_length=500)),
                ('data_add', models.DateTimeField(default=datetime.datetime(2020, 9, 24, 8, 4, 43, 533647, tzinfo=utc), editable=False)),
                ('data_modif', models.DateTimeField(default=datetime.datetime(2020, 9, 24, 8, 4, 43, 533704, tzinfo=utc))),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.medico')),
                ('pac', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='leito',
            name='setor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.setor'),
        ),
    ]
