# Generated by Django 3.1 on 2021-10-26 22:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leito',
            name='label',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='fono',
            field=models.CharField(default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='vacina',
            field=models.CharField(default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 22, 35, 19, 334547, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 22, 35, 19, 334572, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 22, 35, 19, 333549, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 22, 35, 19, 333588, tzinfo=utc)),
        ),
    ]
