# Generated by Django 2.2.1 on 2019-05-29 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190529_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 17, 41, 39, 13637, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 17, 41, 39, 13658, tzinfo=utc)),
        ),
    ]
