# Generated by Django 3.1 on 2021-10-26 22:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_leito_ocorrencia_add_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leito',
            name='label',
            field=models.CharField(default=' ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 22, 49, 25, 204140, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 22, 49, 25, 204172, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 22, 49, 25, 202799, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 22, 49, 25, 202842, tzinfo=utc)),
        ),
    ]
