# Generated by Django 3.1 on 2021-10-26 22:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_leito_alter_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leito',
            name='label',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 22, 54, 27, 263338, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 22, 54, 27, 263364, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 22, 54, 27, 262228, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 22, 54, 27, 262276, tzinfo=utc)),
        ),
    ]
