# Generated by Django 2.2.1 on 2019-05-29 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190529_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 17, 43, 40, 412497, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 17, 43, 40, 412518, tzinfo=utc)),
        ),
    ]
