# Generated by Django 2.2.1 on 2019-06-30 14:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190529_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='hospital',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Hospital'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 14, 41, 51, 12171, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 14, 41, 51, 12192, tzinfo=utc)),
        ),
    ]
