# Generated by Django 3.1 on 2021-10-27 00:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_leito_alter_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leito',
            name='label',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 0, 16, 15, 167880, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 0, 16, 15, 167952, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 0, 16, 15, 166638, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 0, 16, 15, 166686, tzinfo=utc)),
        ),
    ]
