# Generated by Django 3.1 on 2022-01-14 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_leito_alter_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='idade',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='igc',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='peso_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='peso_nasc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 15, 39, 35, 661509, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 15, 39, 35, 661538, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 15, 39, 35, 660300, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 15, 39, 35, 660344, tzinfo=utc)),
        ),
    ]
