# Generated by Django 2.2.1 on 2019-06-30 14:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_add_hospital_to_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='leito',
            name='setor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Setor'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 14, 45, 19, 199780, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 14, 45, 19, 199802, tzinfo=utc)),
        ),
    ]
