# Generated by Django 2.2.1 on 2019-07-01 13:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_add_setor_to_leitos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='email',
        ),
        migrations.AddField(
            model_name='medico',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 13, 44, 13, 796196, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 13, 44, 13, 796219, tzinfo=utc)),
        ),
    ]
