# Generated by Django 2.2.1 on 2019-07-10 23:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_add_userid_to_medicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='user_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 23, 50, 32, 640303, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 23, 50, 32, 640351, tzinfo=utc)),
        ),
    ]
