# Generated by Django 2.2.1 on 2019-07-14 21:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_add_hospital_to_medicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='setor',
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 21, 13, 12, 727071, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 21, 13, 12, 727110, tzinfo=utc)),
        ),
    ]
