# Generated by Django 2.2.1 on 2019-07-14 21:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_paciente_leito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 21, 23, 15, 360017, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 21, 23, 15, 360098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paciente_leito',
            name='leito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Leito'),
        ),
    ]
