# Generated by Django 2.2.3 on 2019-07-29 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_pac_leito_02'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='hospitais',
            field=models.ManyToManyField(to='dashboard.Hospital'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 19, 27, 4, 714470, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 19, 27, 4, 714505, tzinfo=utc)),
        ),
    ]
