# Generated by Django 3.0.5 on 2020-04-24 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_add_leito_to_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='hospitais',
            new_name='hospital',
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 13, 51, 32, 440379, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 13, 51, 32, 440423, tzinfo=utc)),
        ),
    ]
