# Generated by Django 3.0.5 on 2020-04-30 21:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_altera_Medico_crm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='hospital',
        ),
        migrations.AddField(
            model_name='medico',
            name='hospital',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Hospital'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 21, 7, 11, 887369, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 21, 7, 11, 887410, tzinfo=utc)),
        ),
    ]
