# Generated by Django 3.0.5 on 2020-05-11 00:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_Medico_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tcle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 0, 20, 8, 732927, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 0, 20, 8, 732948, tzinfo=utc)),
        ),
    ]
