# Generated by Django 3.0.5 on 2020-05-28 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_altera_setor_add_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='setor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Setor'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 28, 9, 17, 45, 781670, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 28, 9, 17, 45, 781718, tzinfo=utc)),
        ),
    ]
