# Generated by Django 3.0.5 on 2020-06-12 13:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_add_setor_Paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 13, 14, 43, 863193, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 13, 14, 43, 863239, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='paciente',
            name='log_med',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Medico'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='status',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 13, 14, 43, 864388, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 13, 14, 43, 864417, tzinfo=utc)),
        ),
    ]
