# Generated by Django 3.0.5 on 2020-07-19 19:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_paciente_add_status_datafields_logmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='acesso_venoso',
            field=models.CharField(default='Não', max_length=40),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='antibiotico',
            field=models.CharField(default='Não', max_length=100),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 19, 32, 38, 672422, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 19, 32, 38, 672453, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 19, 32, 38, 671211, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 19, 32, 38, 671267, tzinfo=utc)),
        ),
    ]
