# Generated by Django 3.1 on 2020-08-25 02:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_model_ocorrencia_av_atb'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='recomendacoes',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 2, 20, 11, 900508, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 2, 20, 11, 900533, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 2, 20, 11, 899545, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_modif',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 2, 20, 11, 899583, tzinfo=utc)),
        ),
    ]
